# --- Ingress-NGINX Installatie ---

- name: Ingress-NGINX installeren
  ansible.builtin.command: >
    kubectl apply -f
    https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: true

- name: Wachten tot ingress controller ready is
  ansible.builtin.command: >
    kubectl wait --namespace {{ ns_ingress }}
    --for=condition=available deployment/ingress-nginx-controller
    --timeout=180s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false
